version: '3.8'
services:
  relayer:
    image: mix2earn/relayer:1.0.6
    restart: unless-stopped
    env_file: ./.env
    environment:
      - PRIVATE_KEY=$PRIVATE_KEY
      - PUBLIC_KEY=$PUBLIC_KEY
      - RPC_URL=$RPC_URL
      - NETWORKS=$NETWORKS
      - URL=$URL
      - CONTRACTS=$CONTRACTS
    ports:
      - $PORT_LOCAL:7002
    stdin_open: true
    tty: true
